// Default empty CV data structure
export const defaultCVData = {
  personal: {
    firstName: '',
    lastName: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
    portfolio: '',
    photo: null,
    summary: '',
    dob: '',
    nationality: '',
    drivingLicense: '',
    postalCode: '',
    country: '',
  },
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  languages: [],
  awards: [],
  courses: [],
  volunteer: [],
  publications: [],
  interests: [],
  references: { type: 'available', items: [] },
  customSections: [],
};

// Demo data for landing page and builder preview (Fully filled US-based profile for John Doe)
export const demoCVData = {
  personal: {
    firstName: 'Abdullah',
    lastName: 'Kishwar',
    title: 'Senior Full-Stack Engineer & Tech Lead',
    email: 'abdullah.kishwar@email.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    postalCode: '94107',
    country: 'United States',
    website: 'abdullahkishwar.dev',
    linkedin: 'linkedin.com/in/abdullahkishwar',
    github: 'github.com/abdullahkishwar',
    portfolio: 'abdullahkishwar.dev',
    photo: null,
    summary:
      'Innovative Senior Full-Stack Engineer with 8+ years of experience building scalable enterprise cloud applications, distributed backend microservices, and modern web architectures. Proven track record leading high-performing engineering teams at top US tech companies.',
    dob: '',
    nationality: 'American',
    drivingLicense: 'Class C',
  },
  experience: [
    {
      id: 'exp-1',
      jobTitle: 'Senior Software Engineer & Tech Lead',
      company: 'Apple',
      location: 'Cupertino, CA',
      startDate: '2022-03',
      endDate: '',
      current: true,
      description: 'Lead engineer for cloud platform services supporting over 120M active users.',
      achievements: [
        'Architected real-time distributed microservices reducing API latency by 42%',
        'Mentored 8 mid-level engineers and established CI/CD automation guidelines company-wide',
        'Spearheaded migration to Next.js and GraphQL, accelerating page load speeds by 65%',
      ],
    },
    {
      id: 'exp-2',
      jobTitle: 'Software Engineer II',
      company: 'Google',
      location: 'Mountain View, CA',
      startDate: '2019-06',
      endDate: '2022-02',
      current: false,
      description: 'Built high-throughput indexing pipelines and distributed data processing systems.',
      achievements: [
        'Engineered scalable data pipelines processing 5TB+ daily telemetry data with 99.999% uptime',
        'Collaborated with product and security teams to achieve SOC2 & GDPR compliance',
        'Received Google Spot Bonus for exceptional architectural refactoring under tight deadlines',
      ],
    },
    {
      id: 'exp-3',
      jobTitle: 'Full-Stack Software Engineer',
      company: 'Stripe',
      location: 'San Francisco, CA',
      startDate: '2017-08',
      endDate: '2019-05',
      current: false,
      description: 'Developed payment onboarding flows and merchant developer tools.',
      achievements: [
        'Redesigned merchant dashboard onboarding flow, increasing checkout completion by +28%',
        'Implemented TypeScript design system and reusable component libraries',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      degree: 'M.S. in Computer Science',
      institution: 'Stanford University',
      location: 'Stanford, CA',
      startDate: '2017-09',
      endDate: '2019-06',
      grade: '3.95 GPA',
      description: 'Specialization in Distributed Systems & Artificial Intelligence. Graduate Research Fellow.',
    },
    {
      id: 'edu-2',
      degree: 'B.S. in Software Engineering',
      institution: 'University of California, Berkeley',
      location: 'Berkeley, CA',
      startDate: '2013-09',
      endDate: '2017-05',
      grade: '3.90 GPA',
      description: 'Dean’s Honor List all semesters. President of ACM Student Chapter.',
    },
  ],
  skills: [
    { id: 'sk-1', name: 'TypeScript / JavaScript', level: 'Expert' },
    { id: 'sk-2', name: 'React / Next.js', level: 'Expert' },
    { id: 'sk-3', name: 'Node.js / Express', level: 'Expert' },
    { id: 'sk-4', name: 'Python / FastAPI', level: 'Advanced' },
    { id: 'sk-5', name: 'AWS & Cloud Architecture', level: 'Expert' },
    { id: 'sk-6', name: 'Docker / Kubernetes', level: 'Advanced' },
    { id: 'sk-7', name: 'PostgreSQL & Redis', level: 'Advanced' },
    { id: 'sk-8', name: 'System Design & Microservices', level: 'Expert' },
    { id: 'sk-9', name: 'GraphQL & RESTful APIs', level: 'Advanced' },
  ],
  projects: [
    {
      id: 'pr-1',
      name: 'CloudScale Event Streamer',
      description: 'High-performance distributed event streaming framework capable of ingesting 250k events/second.',
      technologies: ['TypeScript', 'Rust', 'Kafka', 'Docker'],
      role: 'Creator & Lead Maintainer',
      achievements: ['Over 4,500 GitHub stars and 120k monthly npm downloads'],
      liveUrl: 'cloudscale.dev',
      githubUrl: 'github.com/johndoe/cloudscale',
    },
    {
      id: 'pr-2',
      name: 'AI Agent Pipeline',
      description: 'Real-time multi-agent orchestration framework for automated code verification and testing.',
      technologies: ['Python', 'FastAPI', 'Next.js', 'PostgreSQL'],
      role: 'Lead Architect',
      achievements: ['Adopted by 30+ YC startups in beta testing phase'],
      liveUrl: 'agentpipeline.io',
      githubUrl: 'github.com/johndoe/agentpipeline',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Solutions Architect – Professional',
      issuer: 'Amazon Web Services',
      issueDate: '2022-05',
      expiryDate: '2025-05',
      credentialId: 'AWS-PSA-948102',
      credentialUrl: 'aws.amazon.com/verify/AWS-PSA-948102',
    },
    {
      id: 'cert-2',
      name: 'Certified Kubernetes Administrator (CKA)',
      issuer: 'Cloud Native Computing Foundation (CNCF)',
      issueDate: '2021-08',
      expiryDate: '',
      credentialId: 'CKA-83921-CNCF',
      credentialUrl: 'cncf.io/verify/CKA-83921',
    },
  ],
  languages: [
    { id: 'lang-1', language: 'English', proficiency: 'Native' },
    { id: 'lang-2', language: 'Spanish', proficiency: 'Fluent' },
    { id: 'lang-3', language: 'French', proficiency: 'Conversational' },
  ],
  awards: [
    {
      id: 'aw-1',
      name: 'Google Engineering Innovation Award',
      organization: 'Google Inc.',
      date: '2021-11',
      description: 'Awarded for exceptional architectural contribution to distributed telemetry processing.',
    },
    {
      id: 'aw-2',
      name: 'Stanford University Dean’s Fellowship',
      organization: 'Stanford School of Engineering',
      date: '2018-05',
      description: 'Merit-based graduate fellowship awarded to top 2% of engineering research candidates.',
    },
  ],
  courses: [],
  volunteer: [],
  publications: [],
  interests: [
    { id: 'int-1', name: 'Open Source' },
    { id: 'int-2', name: 'Cloud Computing' },
    { id: 'int-3', name: 'Hiking & National Parks' },
    { id: 'int-4', name: 'Marathon Running' },
  ],
  references: { type: 'available', items: [] },
  customSections: [],
};

// Section metadata
export const sectionMeta = {
  personal: { label: 'Personal Details', icon: 'User', required: true },
  experience: { label: 'Work Experience', icon: 'Briefcase', required: false },
  education: { label: 'Education', icon: 'GraduationCap', required: false },
  skills: { label: 'Skills', icon: 'Zap', required: false },
  projects: { label: 'Projects', icon: 'FolderOpen', required: false },
  certifications: { label: 'Certifications', icon: 'Award', required: false },
  languages: { label: 'Languages', icon: 'Globe', required: false },
  awards: { label: 'Awards', icon: 'Trophy', required: false },
  courses: { label: 'Courses', icon: 'BookOpen', required: false },
  volunteer: { label: 'Volunteer Experience', icon: 'Heart', required: false },
  publications: { label: 'Publications', icon: 'FileText', required: false },
  interests: { label: 'Interests', icon: 'Smile', required: false },
  references: { label: 'References', icon: 'Users', required: false },
};
