// Template registry — all 15 CV templates
export const templates = [
  {
    id: 'minimal',
    name: 'Corporate ATS',
    category: 'Classic',
    description: 'Full-width grey section bars. High readability corporate format.',
    colors: { primary: '#111827', accent: '#4b5563', text: '#111827', background: '#ffffff' },
    font: 'Inter',
    tags: ['corporate', 'classic', 'ATS-friendly', 'grey-bar'],
  },
  {
    id: 'modern',
    name: 'Minimalist Editorial',
    category: 'Contemporary',
    description: 'Refined typography with wide letter-spacing and clean dividers.',
    colors: { primary: '#171717', accent: '#525252', text: '#262626', background: '#ffffff' },
    font: 'Montserrat',
    tags: ['modern', 'editorial', 'contemporary', 'minimal'],
  },
  {
    id: 'professional',
    name: 'Calligraphic Split',
    category: 'Corporate',
    description: 'Elegant script header with two-column split layout.',
    colors: { primary: '#1a1a1a', accent: '#595959', text: '#262626', background: '#ffffff' },
    font: 'Great Vibes',
    tags: ['calligraphic', 'two-column', 'formal', 'elegant'],
  },
  {
    id: 'creative',
    name: 'Luxury Serif',
    category: 'Design',
    description: 'Large stacked display serif with circular icon badges.',
    colors: { primary: '#111111', accent: '#2b2b2b', text: '#1f1f1f', background: '#ffffff' },
    font: 'Cinzel Decorative',
    tags: ['design', 'luxury', 'serif', 'fashion'],
  },
  {
    id: 'executive',
    name: 'Executive ATS',
    category: 'Leadership',
    description: 'Classic heavy-rule header with 3-column bulleted skills.',
    colors: { primary: '#111111', accent: '#333333', text: '#222222', background: '#ffffff' },
    font: 'Inter',
    tags: ['executive', 'leadership', 'ATS', 'classic'],
  },
  {
    id: 'developer',
    name: 'Pop Art Designer',
    category: 'Creative',
    description: 'Playful yellow brush-stroke headers with organic photo cutout and confetti dots.',
    colors: { primary: '#182672', accent: '#FFD026', text: '#222222', background: '#F4F4F6' },
    font: 'Cabinet Grotesk',
    tags: ['creative', 'pop-art', 'graphic-designer', 'playful'],
  },
  {
    id: 'ats',
    name: 'Botanical Earthy',
    category: 'Minimalist',
    description: 'Warm taupe tones, hand-drawn botanical leaves, and organic rounded pill headers.',
    colors: { primary: '#2C241E', accent: '#C8B8A6', text: '#2C241E', background: '#F9F7F2' },
    font: 'Bodoni Moda',
    tags: ['botanical', 'earthy', 'organic', 'minimalist'],
  },
  {
    id: 'sidebar',
    name: 'Creator Scrapbook',
    category: 'Creative',
    description: 'Purple watercolor splash, realistic sticky note contact card, and playful doodles.',
    colors: { primary: '#18181B', accent: '#A855F7', text: '#1F1F1F', background: '#FAF9F6' },
    font: 'Permanent Marker',
    tags: ['creator', 'social-media', 'doodle', 'scrapbook'],
  },
  {
    id: 'bold',
    name: 'Monochromatic Modern',
    category: 'Tech',
    description: 'High-contrast black & white architecture with monogrammed contact matrix.',
    colors: { primary: '#000000', accent: '#555555', text: '#1A1A1A', background: '#FFFFFF' },
    font: 'Plus Jakarta Sans',
    tags: ['monochromatic', 'modern', 'developer', 'clean'],
  },
  {
    id: 'elegant',
    name: 'Editorial Crimson',
    category: 'Editorial',
    description: 'Bold display typography interwoven with script accents and high-fashion layout.',
    colors: { primary: '#BA1D24', accent: '#222222', text: '#222222', background: '#F5F4EF' },
    font: 'Anton',
    tags: ['editorial', 'fashion', 'crimson', 'typography'],
  },
  {
    id: 'compact',
    name: 'Parisian Chic',
    category: 'Chic',
    description: 'Soft lavender-grey header banner with elegant calligraphic signature script.',
    colors: { primary: '#1E1B24', accent: '#7C748C', text: '#2B2B2B', background: '#FFFFFF' },
    font: 'Alex Brush',
    tags: ['parisian', 'chic', 'calligraphic', 'minimalist'],
  },
  {
    id: 'nordic',
    name: 'Organic Pastel',
    category: 'Creative',
    description: 'Gentle organic blob waves in peach and sage with condensed bold typography.',
    colors: { primary: '#253835', accent: '#D98877', text: '#2B3A37', background: '#FFFFFF' },
    font: 'League Gothic',
    tags: ['organic', 'pastel', 'waves', 'contemporary'],
  },
  {
    id: 'academic',
    name: 'Midnight Timeline',
    category: 'Modern',
    description: 'Deep midnight sidebar with circular portrait and connected vertical timeline nodes.',
    colors: { primary: '#18181D', accent: '#33333D', text: '#222222', background: '#FFFFFF' },
    font: 'Montserrat',
    tags: ['midnight', 'timeline', 'dark-sidebar', 'high-contrast'],
  },
  {
    id: 'startup',
    name: 'Infographic Roadmap',
    category: 'Infographic',
    description: 'Teal & slate career roadmap graph with milestone icons and mountain peak art.',
    colors: { primary: '#264653', accent: '#2A9D8F', text: '#264653', background: '#FBFBFA' },
    font: 'Plus Jakarta Sans',
    tags: ['infographic', 'roadmap', 'milestones', 'visual'],
  },
  {
    id: 'magazine',
    name: 'Linen Executive',
    category: 'Executive',
    description: 'Warm linen background with luxury beige card containers and spaced titles.',
    colors: { primary: '#1F1D1A', accent: '#F2ECE3', text: '#1F1D1A', background: '#FAF8F5' },
    font: 'Plus Jakarta Sans',
    tags: ['linen', 'executive', 'luxury', 'beige'],
  },
];

export const getTemplate = (id) => templates.find((t) => t.id === id) || templates[0];
